version: '3'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/social-media-poster
  #   depends_on:
  #     - mongodb
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

volumes:
  mongodb_data: